"""Build a self-contained "Export to Cyfronet" bundle (a ZIP).

The bundle lets the user train the traffic lights on Ares with no extra wiring:
unzip → set the PLGrid grant → ``sbatch optimize_job.sh``. The cluster runs the
parallel genetic algorithm and writes ``result/optimization_result.json``, which
is imported back into the dashboard to visualize the trained plan.

Contents:
  scenario.yaml            cluster-tuned config (bigger GA than the local run)
  net.net.xml, routes...   the exact network + demand built in the dashboard
  optimize_job.sh          ready-to-submit SLURM script
  requirements.txt         cluster Python deps (eclipse-sumo wheel = in-process libsumo)
  README_CYFRONET.md       3-step instructions
  src/...                  the project source, so the bundle is standalone
"""
from __future__ import annotations

import copy
import io
import zipfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]

_SBATCH = r"""#!/bin/bash -l
#SBATCH --job-name=traffic-train
#SBATCH --account=@@GRANT@@
#SBATCH --partition=plgrid
#SBATCH --nodes=@@NODES@@
#SBATCH --ntasks=@@NTASKS@@
#SBATCH --cpus-per-task=1
#SBATCH --time=@@WALLTIME@@
#SBATCH --output=result/train_%j.log
#
# Train traffic-light timings on Cyfronet Ares (parallel genetic algorithm).
#   1) unzip this bundle
#   2) set --account above to your PLGrid grant id (e.g. plgYYYY-cpu)
#   3) sbatch optimize_job.sh
set -euo pipefail
cd "$SLURM_SUBMIT_DIR"
mkdir -p result

# --- one-time environment setup (run once, then comment out) ----------------
# module load Miniconda3/23.3.1-0
# conda create -y -n traffic python=3.11
# conda activate traffic
# pip install -r requirements.txt
# ---------------------------------------------------------------------------
module load Miniconda3/23.3.1-0 || true
conda activate traffic

# SUMO comes from the eclipse-sumo wheel (in-process libsumo, no binary needed).
export SUMO_HOME="$(python -c 'import sumolib, os; print(os.path.dirname(os.path.dirname(sumolib.__file__)))' 2>/dev/null || echo)"

# @@NTASKS@@ MPI ranks: rank 0 is the master, the rest evaluate the GA population.
srun python -m mpi4py.futures -m src.ga.parallel \
    --config scenario.yaml --out . \
    --result result/optimization_result.json \
    --csv result/scaling.csv

echo "DONE -> result/optimization_result.json (import this back into the dashboard)"
"""

_REQS = """\
eclipse-sumo>=1.20
deap>=1.4
mpi4py>=3.1
pyyaml>=6.0
numpy>=1.26
"""

_README = """\
# Train traffic lights on Cyfronet Ares

This bundle was generated by the Urban Traffic Controller dashboard. It runs a
parallel genetic algorithm that learns the traffic-light timings for the network
you designed, then produces a result you import back into the dashboard.

## Steps

1. Copy this ZIP to Ares and unzip it:
   ```
   unzip {zipname}
   cd {stem}
   ```
2. Open `optimize_job.sh` and set `--account` to your PLGrid grant id
   (and adjust `--ntasks` / `--time` if you like).
3. First time only — create the environment (commands are also in the script):
   ```
   module load Miniconda3/23.3.1-0
   conda create -y -n traffic python=3.11 && conda activate traffic
   pip install -r requirements.txt
   ```
4. Submit the training job:
   ```
   sbatch optimize_job.sh
   ```

## Result

When the job finishes you get `result/optimization_result.json` — the trained
signal plan (best timings, baseline vs optimized delay, learning curve). Download
it and load it in the dashboard via **Import result** to see before/after.

`result/scaling.csv` additionally records (workers, elapsed) for the scaling study.
"""


def _cluster_cfg(cfg: dict, name: str) -> dict:
    """Beef up the GA so the cluster does real training, not the quick local run."""
    out = copy.deepcopy(cfg)
    out["name"] = name
    ga = out.setdefault("ga", {})
    ga["population"] = max(int(ga.get("population", 20)), 64)
    ga["generations"] = max(int(ga.get("generations", 12)), 30)
    return out


def _iter_source_files():
    """Yield (arcname, bytes) for the project source needed to run on the cluster."""
    for sub in ("src",):
        base = ROOT / sub
        for path in base.rglob("*.py"):
            if "__pycache__" in path.parts:
                continue
            yield path.relative_to(ROOT).as_posix(), path.read_bytes()


def build_bundle(cfg: dict, net_path: str, routes_path: str, *,
                 name: str = "exported", grant: str = "PLG_GRANT_ID",
                 ntasks: int = 24, nodes: int = 1,
                 walltime: str = "02:00:00") -> bytes:
    """Assemble the ZIP in memory and return its bytes."""
    sbatch = (_SBATCH.replace("@@GRANT@@", grant or "PLG_GRANT_ID")
              .replace("@@NODES@@", str(nodes))
              .replace("@@NTASKS@@", str(ntasks))
              .replace("@@WALLTIME@@", walltime))
    zipname = f"cyfronet_{name}.zip"
    readme = _README.format(zipname=zipname, stem=f"cyfronet_{name}")
    scenario_yaml = ("# Auto-generated by the dashboard's Export to Cyfronet.\n"
                     "# GA enlarged vs the local run so the cluster does real training.\n"
                     + yaml.safe_dump(_cluster_cfg(cfg, name), sort_keys=False))

    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("scenario.yaml", scenario_yaml)
        zf.write(net_path, "net.net.xml")
        zf.write(routes_path, "routes.rou.xml")
        zf.writestr("optimize_job.sh", sbatch)
        zf.writestr("requirements.txt", _REQS)
        zf.writestr("README_CYFRONET.md", readme)
        for arcname, data in _iter_source_files():
            zf.writestr(arcname, data)
    return buf.getvalue()
